name: "random reshare"

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  reshare:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: "check token"
        env:
          FRMENV_FBTOKEN: ${{ secrets.GITHUB_FBTOKEN }}
        run: |
          echo "Token loaded: ${FRMENV_FBTOKEN:0:4}****"

      - name: "run random reshare"
        env:
          FRMENV_FBTOKEN: ${{ secrets.GITHUB_FBTOKEN }}
          FRMENV_API_ORIGIN: "https://graph.facebook.com"
          FRMENV_FBAPI_VER: "v23.0"
        run: bash ./scripts/reshare_random.sh
