name: "random reshare"

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  reshare:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: "check token"
        env:
          FRMENV_FBTOKEN: ${{ secrets.FRMENV_FBTOKEN }}
        run: echo 'Token loaded: '$(echo $FRMENV_FBTOKEN | cut -c1-4)'****'

      - name: "run random reshare"
        env:
          FRMENV_FBTOKEN: ${{ secrets.FRMENV_FBTOKEN }}
          FRMENV_API_ORIGIN: "https://graph.facebook.com"
          FRMENV_FBAPI_VER: "v22.0"
        run: bash ./scripts/reshare_random.sh
