name: "random reshare"

on:
  schedule:
    - cron: "0 7,15,23 * * *"
  workflow_dispatch:

jobs:
  reshare:
    runs-on: ubuntu-latest
    env:
      FRMENV_FBTOKEN: ${{ secrets.TOK_FB }}
      FRMENV_API_ORIGIN: "https://graph.facebook.com"
      FRMENV_FBAPI_VER: "v23.0"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: "check token"
        run: |
          if [[ -z "$FRMENV_FBTOKEN" ]]; then
            echo "❌ Token is empty!"
            exit 1
          fi
          echo "Token loaded: ${FRMENV_FBTOKEN:0:4}****"

      - name: "run random reshare"
        run: bash ./scripts/reshare_random.sh
